
export const FALLBACK_TENDERS = [
    {
        id: "fallback-1",
        external_id: "FALLBACK_001",
        tender_id: "SOLAR-2026-001",
        title: "Installation of 500KW Grid Connected Solar PV System at AIIMS Bhubaneswar",
        department: "Solar Power Plant",
        location: "Odisha",
        estimated_value: 45000000,
        amount: "₹4.50 Crores",
        bid_deadline: "2026-03-02",
        deadline: "2026-03-02",
        category: "CONSTRUCTION",
        status: "ACTIVE",
        temperature: "HOT",
        source_url: "https://etenders.gov.in/eprocure/app",
        source: "https://etenders.gov.in/eprocure/app"
    },
    {
        id: "fallback-2",
        external_id: "FALLBACK_002",
        tender_id: "EV-CHRG-042",
        title: "Setting up of 10 Ultra Fast EV Charging Stations along Mumbai-Pune Expressway",
        department: "EV Charger",
        location: "Maharashtra",
        estimated_value: 82000000,
        amount: "₹8.20 Crores",
        bid_deadline: "2026-02-25",
        deadline: "2026-02-25",
        category: "SERVICES",
        status: "ACTIVE",
        temperature: "TRENDING",
        source_url: "https://gem.gov.in/",
        source: "https://gem.gov.in/"
    },
    {
        id: "fallback-3",
        external_id: "FALLBACK_003",
        tender_id: "HYDRO-MOD-99",
        title: "Modernization of Control & Instrumentation system for Hirakud Hydro Power House",
        department: "Energy",
        location: "Odisha",
        estimated_value: 125000000,
        amount: "₹12.50 Crores",
        bid_deadline: "2026-03-27",
        deadline: "2026-03-27",
        category: "SUPPLY",
        status: "ACTIVE",
        temperature: "WARM",
        source_url: "https://tendersodisha.gov.in/",
        source: "https://tendersodisha.gov.in/"
    },
    {
        id: "fallback-4",
        external_id: "FALLBACK_004",
        tender_id: "WATER-PIPE-202",
        title: "Laying & Jointing of HDPE Water Supply Pipeline for SMART City Project Ranchi",
        department: "Water & Waste Management",
        location: "Jharkhand",
        estimated_value: 21000000,
        amount: "₹2.10 Crores",
        bid_deadline: "2026-02-17",
        deadline: "2026-02-17",
        category: "CONSTRUCTION",
        status: "ACTIVE",
        temperature: "HOT",
        source_url: "https://jharkhandtenders.gov.in/",
        source: "https://jharkhandtenders.gov.in/"
    },
    {
        id: "fallback-5",
        external_id: "FALLBACK_005",
        tender_id: "GREEN-H2-RES",
        title: "Research & Development contract for Green Hydrogen Electrolyzer efficiency optimization",
        department: "Green Hydrogen",
        location: "Delhi",
        estimated_value: 15000000,
        amount: "₹1.50 Crores",
        bid_deadline: "2026-04-10",
        deadline: "2026-04-10",
        category: "SERVICES",
        status: "ACTIVE",
        temperature: "PENDING",
        source_url: "https://eprocure.gov.in/cppp/",
        source: "https://eprocure.gov.in/cppp/"
    },
    {
        id: "fallback-6",
        external_id: "FALLBACK_006",
        tender_id: "DRONE-AGRI-01",
        title: "Procurement of Agricultural Drones for Precision Farming Demonstration",
        department: "Drone",
        location: "Punjab",
        estimated_value: 9500000,
        amount: "₹0.95 Crores",
        bid_deadline: "2026-02-24",
        deadline: "2026-02-24",
        category: "SUPPLY",
        status: "ACTIVE",
        temperature: "TRENDING",
        source_url: "https://etender.punjab.gov.in/",
        source: "https://etender.punjab.gov.in/"
    },
    {
        id: "fallback-7",
        external_id: "FALLBACK_007",
        tender_id: "BESS-STOR-55",
        title: "Supply and Installation of 100MWh Battery Energy Storage System (BESS)",
        department: "BESS",
        location: "Gujarat",
        estimated_value: 185000000,
        amount: "₹18.50 Crores",
        bid_deadline: "2026-04-15",
        deadline: "2026-04-15",
        category: "SUPPLY",
        status: "ACTIVE",
        temperature: "HOT",
        source_url: "https://eprocure.gov.in/cppp/",
        source: "https://eprocure.gov.in/cppp/"
    },
    {
        id: "fallback-8",
        external_id: "FALLBACK_008",
        tender_id: "STREET-LED-88",
        title: "Installation of Smart LED Street Lighting System with IoT Control",
        department: "Street Lights",
        location: "Karnataka",
        estimated_value: 28000000,
        amount: "₹2.80 Crores",
        bid_deadline: "2026-03-20",
        deadline: "2026-03-20",
        category: "CONSTRUCTION",
        status: "ACTIVE",
        temperature: "WARM",
        source_url: "https://etenders.gov.in/eprocure/app",
        source: "https://etenders.gov.in/eprocure/app"
    },
    {
        id: "fallback-9",
        external_id: "FALLBACK_009",
        tender_id: "COLD-STOR-33",
        title: "Construction of Solar-Powered Cold Storage Facility for Agricultural Produce",
        department: "Cold Storage",
        location: "Haryana",
        estimated_value: 35000000,
        amount: "₹3.50 Crores",
        bid_deadline: "2026-03-30",
        deadline: "2026-03-30",
        category: "CONSTRUCTION",
        status: "ACTIVE",
        temperature: "TRENDING",
        source_url: "https://eprocure.gov.in/cppp/",
        source: "https://eprocure.gov.in/cppp/"
    },
    {
        id: "fallback-10",
        external_id: "FALLBACK_010",
        tender_id: "PUMP-SOLAR-77",
        title: "Supply of 500 Solar Water Pumping Systems for Irrigation",
        department: "Pump Polarization",
        location: "Rajasthan",
        estimated_value: 42000000,
        amount: "₹4.20 Crores",
        bid_deadline: "2026-04-05",
        deadline: "2026-04-05",
        category: "SUPPLY",
        status: "ACTIVE",
        temperature: "HOT",
        source_url: "https://rajasthan.gov.in/",
        source: "https://rajasthan.gov.in/"
    },
    {
        id: "fallback-11",
        external_id: "FALLBACK_011",
        tender_id: "CBG-PLANT-22",
        title: "Development of Compressed Biogas (CBG) Production Plant",
        department: "CBG",
        location: "Uttar Pradesh",
        estimated_value: 55000000,
        amount: "₹5.50 Crores",
        bid_deadline: "2026-04-20",
        deadline: "2026-04-20",
        category: "CONSTRUCTION",
        status: "ACTIVE",
        temperature: "WARM",
        source_url: "https://etenders.gov.in/eprocure/app",
        source: "https://etenders.gov.in/eprocure/app"
    },
    {
        id: "fallback-12",
        external_id: "FALLBACK_012",
        tender_id: "FUEL-CELL-99",
        title: "Procurement of Hydrogen Fuel Cell Systems for Public Transport",
        department: "Fuel Cell",
        location: "Tamil Nadu",
        estimated_value: 78000000,
        amount: "₹7.80 Crores",
        bid_deadline: "2026-05-01",
        deadline: "2026-05-01",
        category: "SUPPLY",
        status: "ACTIVE",
        temperature: "TRENDING",
        source_url: "https://tntenders.gov.in/",
        source: "https://tntenders.gov.in/"
    }
];
